USE master;
GO

IF DB_ID('SIGAU_RESTORE_TEST') IS NOT NULL
BEGIN
    ALTER DATABASE SIGAU_RESTORE_TEST
    SET SINGLE_USER
    WITH ROLLBACK IMMEDIATE;

    DROP DATABASE SIGAU_RESTORE_TEST;
END
GO

RESTORE DATABASE SIGAU_RESTORE_TEST
FROM DISK = N'H:\SQLServer\Backups\SIGAU\SIGAU_FULL_20260606.bak'
WITH
MOVE 'SIGAU_Primary'
TO 'E:\SQLServer\Data\SIGAU\SIGAU_RESTORE_TEST_Primary.mdf',

MOVE 'SIGAU_Core_01'
TO 'E:\SQLServer\Data\SIGAU\SIGAU_RESTORE_TEST_Core.ndf',

MOVE 'SIGAU_Academico_01'
TO 'E:\SQLServer\Data\SIGAU\SIGAU_RESTORE_TEST_Academico.ndf',

MOVE 'SIGAU_Seguridad_01'
TO 'E:\SQLServer\Data\SIGAU\SIGAU_RESTORE_TEST_Seguridad.ndf',

MOVE 'SIGAU_Log'
TO 'F:\SQLServer\Logs\SIGAU\SIGAU_RESTORE_TEST_Log.ldf',

MOVE 'SIGAU_MemoryOptimized'
TO 'E:\SQLServer\Data\SIGAU\MemoryOptimized_RESTORE_TEST',

RECOVERY,
REPLACE,
STATS = 10;
GO

SELECT
    name,
    recovery_model_desc,
    state_desc
FROM sys.databases
WHERE name = 'SIGAU_RESTORE_TEST';
GO
